server:
  port: 8383
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./test.db
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update